Update getNeuroML.py
Fixed for python3.6 for following error.

```
TypeError: 'in <string>' requires string as left operand, not bytes
```
Not sure if it will break python2.